services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000" # PHP-FPM port
    depends_on:
      - db
    networks:
      - blog_platform

  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog_platform

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80" # App will be accessible at http://localhost:8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - blog_platform

volumes:
  pgdata:

networks:
  blog_platform:
    driver: bridge
